version: '3.5'
services:
  zabbix-postgres-server:
    image: zabbix-postgresql:latest
    hostname: zabbix-postgresgl
    restart: always
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: "zabbix"
      POSTGRES_DB: "zabbix"
      POSTGRES_PASSWORD: "PASSWORD"
    networks:
      default:
        ipv4_address: 158.160.12.255
    volumes:
      - /opt/zabbix/pgsql/data:/var/lib/pgsql

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    container_name: zabbix-server
    hostname: zabbix-server
    restart: always
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: "zabbix"
      POSTGRES_DB: "zabbix"
      POSTGRES_PASSWORD: "PASSWORD"
    networks:
      default:
        ipv4_address: 158.160.12.255
    ports:
      - 10051:10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /zabbix-data/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - /zabbix-data/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - /zabbix-data/export:/var/lib/zabbix/export:rw
      - /zabbix-data/modules:/var/lib/zabbix/modules:ro
      - /zabbix-data/enc:/var/lib/zabbix/enc:ro
      - /zabbix-data/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - /zabbix-data/mibs:/var/lib/zabbix/mibs:ro
      - /zabbix-data/snmptraps:/var/lib/zabbix/snmptraps:rw
    depends_on:
      - postgres-server

  zabbix-web-apahe-pgsql:
