version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.17.8
    volumes:
      - ./configs/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml;ro
      - ./docker_volumes/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms8g -Xmx8g"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "cZarda0K9RYDKf4f42aY"
      discovery.type: single-node
    networks:
      - elk
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:7.17.8
    container_name: kibana
    hostname: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${elastic}
      - ELASTICSEARCH_PASSWORD=${cZarda0K9RYDKf4f42aY}
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
